import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 1.0

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetbrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetbrainsMono Nerd Font", style = "Italic" }
size = 12

[env]
TERM = "xterm-256color"
